# Generated by Django 4.1.3 on 2023-01-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="creation_date",
        ),
    ]
